CC=nvcc
DEVICES=2
LOG_FREQ=0
CUDA_DIRECTORY=/usr/local/cuda-7.5
CFLAGS=-c -arch=sm_37 -O3 -I$(CUDA_DIRECTORY)/include -DNUM_THREADS=$(DEVICES) -DLOG_FREQ=$(LOG_FREQ) #-D__SINGLE_PREC__
RESTARTFLAGS=-D__RESTARTING__
LDFLAGS=-L$(CUDA_DIRECTORY)/lib64 -lcufft
SOURCES=STOMP.cu
OBJECTS=STOMP.o
RESTARTEX=STOMPrestart
RESTARTOBJECTS=STOMPrestart.o
EXECUTABLE=STOMP

all: $(SOURCES) $(EXECUTABLE)

restart: $(SOURCES) $(RESTARTEX)


    
$(EXECUTABLE): $(OBJECTS)  $(SOURCES)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@
	
$(RESTARTEX): $(RESTARTOBJECTS)
	$(CC) $(LDFLAGS) $(RESTARTOBJECTS) -o $@

STOMPrestart.o:
	$(CC) $(CFLAGS) $(RESTARTFLAGS) STOMP.cu -o $@

STOMP.o:
	$(CC) $(CFLAGS) STOMP.cu -o $@
	
clean:
	rm -f *.o STOMP STOMPrestart
